a = input("Digite qualquer coisa: ")
print("O tipo primitivo desse valor é", type(a))
print("Só tem espaços?", a.isspace())
print("É um número?", a.isnumeric())
print("É alfabético?", a.isalpha())
print("É alfanumérico?", a.isalnum())
print("Tudo está em maiúsculo?", a.isupper())
print("Tudo está em minúsculo?", a.islower())
print("Está capitalizado?", a.istitle())